version: '3.8'

services:
  notification_db:
    image: postgres:15
    container_name: notification_db
    environment:
      POSTGRES_DB: markup_notification_db
      POSTGRES_USER: notification_user
      POSTGRES_PASSWORD: notification_pass
    ports:
      - "5434:5432"
    volumes:
      - notification_pg_data:/var/lib/postgresql/data
      - ./markupbd.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  notification_pg_data:
